export enum Action {
    LIST = 'LIST',
    CREATE = 'CREATE',
    CREATEPJ = 'CREATEPJ',
    CREATEORG= 'CREATEORG',
    CREATEMEM= 'CREATEMEM',
    UPLOADPA = 'UPLOADPA',
    CREATEAR = 'CREATEAR',
    CREATEOP = 'CREATEOP',
    UPDATEPA = 'UPDATEPA',
    CREATEOB = 'CREATEOB',
}